# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-20 06:59
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('background_photo', '0002_auto_20190619_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='resize_photo',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='story1399'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='photo',
            field=smartfields.fields.ImageField(upload_to='story1399'),
        ),
    ]
