# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-20 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_photo', '0003_auto_20190620_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='resize_photo',
            field=models.ImageField(blank=True, null=True, upload_to='story1399'),
        ),
    ]
