# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-20 07:23
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('background_photo', '0004_auto_20190620_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='photo',
            field=smartfields.fields.ImageField(blank=True, null=True, upload_to='story1399'),
        ),
    ]
