# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-06-21 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_photo', '0006_auto_20190620_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='original_photo',
            field=models.ImageField(blank=True, null=True, upload_to='story1399'),
        ),
    ]
